from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion,django.utils.timezone,uuid
class Migration(migrations.Migration):
 initial=True
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='Plan',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=20,unique=True)),('name',models.CharField(max_length=50)),('price_monthly',models.DecimalField(decimal_places=2,default=0,max_digits=9)),('meeting_minutes',models.PositiveIntegerField(blank=True,help_text='Blank = unlimited',null=True)),('max_participants',models.PositiveIntegerField(default=4)),('max_file_mb',models.PositiveIntegerField(default=5)),('video_quality',models.CharField(default='720p',max_length=20)),('screen_share',models.BooleanField(default=True)),('whiteboard',models.BooleanField(default=True)),('recording',models.BooleanField(default=False)),('custom_branding',models.BooleanField(default=False)),('active',models.BooleanField(default=True)),('display_order',models.PositiveIntegerField(default=0))],options={'ordering':['display_order','price_monthly']}),
  migrations.CreateModel(name='AppSetting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('key',models.CharField(max_length=100,unique=True)),('value',models.TextField(blank=True)),('description',models.CharField(blank=True,max_length=255)),('updated_at',models.DateTimeField(auto_now=True))]),
  migrations.CreateModel(name='Meeting',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(default='NexaRoom Meeting',max_length=120)),('status',models.CharField(choices=[('scheduled','Scheduled'),('live','Live'),('ended','Ended')],default='scheduled',max_length=12)),('scheduled_for',models.DateTimeField(blank=True,null=True)),('started_at',models.DateTimeField(blank=True,null=True)),('ended_at',models.DateTimeField(blank=True,null=True)),('duration_limit_minutes',models.PositiveIntegerField(blank=True,null=True)),('max_participants',models.PositiveIntegerField(default=4)),('locked',models.BooleanField(default=False)),('allow_screen_share',models.BooleanField(default=True)),('allow_whiteboard',models.BooleanField(default=True)),('allow_files',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('host',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hosted_meetings',to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']}),
  migrations.CreateModel(name='Subscription',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('active',models.BooleanField(default=True)),('started_at',models.DateTimeField(default=django.utils.timezone.now)),('expires_at',models.DateTimeField(blank=True,null=True)),('updated_at',models.DateTimeField(auto_now=True)),('plan',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='subscriptions',to='core.plan')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='subscription',to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='MeetingParticipant',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('joined_at',models.DateTimeField(auto_now_add=True)),('left_at',models.DateTimeField(blank=True,null=True)),('is_host',models.BooleanField(default=False)),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='participants',to='core.meeting')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='meeting_participations',to=settings.AUTH_USER_MODEL))],options={'ordering':['joined_at']}),
  migrations.CreateModel(name='SharedFile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('original_name',models.CharField(max_length=255)),('size_bytes',models.BigIntegerField(default=0)),('mime_type',models.CharField(blank=True,max_length=120)),('encrypted',models.BooleanField(default=True)),('shared_at',models.DateTimeField(auto_now_add=True)),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='shared_files',to='core.meeting')),('sender',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
  migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('detail',models.TextField(blank=True)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']})]
